import Image from 'next/image'
import { ChevronDown, Clock3, MapPin, PackageCheck, Sprout, Star, Warehouse } from 'lucide-react'
import type { Article, FAQ, Nutrition, ProductDetail, Recipe, Review, Specification } from '@/types/product'
import { SectionHeading } from '@/components/ui/section-heading'

export function ProductHero({ product }: { product: ProductDetail }) {
  return <div className="flex flex-col gap-6 border-b border-border pb-8"><p className="eyebrow">{product.eyebrow}</p><h1 className="max-w-2xl font-serif text-5xl leading-[0.95] text-pretty text-foreground sm:text-6xl lg:text-7xl">{product.name}</h1><p className="max-w-xl text-lg leading-relaxed text-muted-foreground">{product.shortDescription}</p><div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-sm"><span className="font-semibold text-foreground">{product.price}</span><span className="text-muted-foreground">{product.packSize}</span><span className="inline-flex items-center gap-1 text-accent"><Star className="size-4 fill-current" aria-hidden="true" /> {product.rating} <span className="text-muted-foreground">({product.reviewCount} reviews)</span></span></div></div>
}

export function ProductInfo({ product }: { product: ProductDetail }) {
  return <div className="grid gap-4 sm:grid-cols-2"><InfoItem icon={MapPin} label="Origin" value={product.region} /><InfoItem icon={Sprout} label="Harvest" value={product.harvest} /><InfoItem icon={PackageCheck} label="Method" value={product.method} /><InfoItem icon={Warehouse} label="Storage" value="Cool, dry cupboard" /></div>
}

function InfoItem({ icon: Icon, label, value }: { icon: typeof MapPin; label: string; value: string }) { return <div className="flex gap-3 border border-border bg-surface p-4"><Icon className="mt-0.5 size-5 shrink-0 text-secondary" aria-hidden="true" /><div><p className="eyebrow text-[0.65rem]">{label}</p><p className="mt-1 text-sm leading-relaxed text-foreground">{value}</p></div></div> }

export function ProducerProfileCard({ product }: { product: ProductDetail }) { return <article className="grid gap-6 bg-primary p-6 text-primary-foreground sm:grid-cols-[180px_1fr] sm:p-8"><div className="relative aspect-square overflow-hidden"><Image src={product.producer.image} alt={`Portrait and landscape from ${product.producer.name}`} fill sizes="180px" className="object-cover" /></div><div><p className="eyebrow text-primary-foreground/70">The maker behind the bottle</p><h3 className="mt-2 font-serif text-4xl">{product.producer.name}</h3><p className="mt-1 text-sm text-primary-foreground/70">{product.producer.place}</p><p className="mt-5 max-w-xl text-sm leading-relaxed text-primary-foreground/80">{product.producer.story}</p><a href="#producer-story" className="mt-6 inline-flex min-h-11 items-center border-b border-accent text-sm font-semibold text-accent">Read their story</a></div></article> }

export function RecipeCard({ recipe }: { recipe: Recipe }) { return <article className="group"><div className="relative aspect-[4/3] overflow-hidden bg-surface-muted"><Image src={recipe.image.src} alt={recipe.image.alt} fill sizes="(max-width: 768px) 90vw, 33vw" className="object-cover transition-transform duration-300 group-hover:scale-105" /></div><div className="flex items-center gap-2 pt-4 text-xs text-muted-foreground"><Clock3 className="size-4 text-secondary" aria-hidden="true" />{recipe.time}</div><h3 className="mt-2 font-serif text-3xl text-foreground">{recipe.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{recipe.description}</p></article> }

export function NutritionCard({ items }: { items: Nutrition[] }) { return <div className="grid gap-px border border-border bg-border sm:grid-cols-4">{items.map((item) => <div key={item.label} className="bg-surface p-4"><p className="eyebrow text-[0.62rem]">{item.label}</p><p className="mt-2 font-serif text-3xl text-foreground">{item.value}</p><p className="mt-1 text-xs text-muted-foreground">{item.note}</p></div>)}</div> }

export function SpecificationTable({ items }: { items: Specification[] }) { return <dl className="divide-y divide-border border-y border-border">{items.map((item) => <div key={item.label} className="grid gap-2 py-4 sm:grid-cols-[180px_1fr]"><dt className="text-sm text-muted-foreground">{item.label}</dt><dd className="text-sm font-semibold text-foreground">{item.value}</dd></div>)}</dl> }

export function FAQAccordion({ items }: { items: FAQ[] }) { return <div className="divide-y divide-border border-y border-border">{items.map((item) => <details key={item.question} className="group py-5"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-4 text-base font-semibold text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><span>{item.question}</span><ChevronDown className="size-5 shrink-0 transition-transform duration-200 group-open:rotate-180" aria-hidden="true" /></summary><p className="max-w-2xl pt-3 text-sm leading-relaxed text-muted-foreground">{item.answer}</p></details>)}</div> }

export function ReviewCard({ review }: { review: Review }) { return <article className="border border-border bg-surface p-5"><div className="flex items-center justify-between gap-3"><div><p className="font-semibold text-foreground">{review.name}</p><p className="text-xs text-muted-foreground">{review.location} · {review.date}</p></div><span className="inline-flex items-center gap-1 text-sm text-accent"><Star className="size-4 fill-current" aria-hidden="true" /> {review.rating}</span></div><p className="mt-4 text-sm leading-relaxed text-muted-foreground">“{review.body}”</p></article> }

export function ArticleCard({ article }: { article: Article }) { return <article className="group grid gap-5 sm:grid-cols-[220px_1fr]"><div className="relative aspect-[4/3] overflow-hidden bg-surface-muted"><Image src={article.image.src} alt={article.image.alt} fill sizes="220px" className="object-cover transition-transform duration-300 group-hover:scale-105" /></div><div><p className="eyebrow">Kitchen Wisdom · {article.readTime}</p><h3 className="mt-2 font-serif text-3xl text-foreground">{article.title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{article.excerpt}</p></div></article> }

export function ProductSectionTitle({ eyebrow, title, intro }: { eyebrow: string; title: string; intro?: string }) { return <SectionHeading eyebrow={eyebrow} title={title} copy={intro} /> }
