module.exports = {
  testEnvironment: "node",
  testTimeout: 45000,
  testMatch: [
    "**/tests/postgresql_integration.test.js",
    "**/tests/auth.test.js",
    "**/tests/auth_full_verification.test.js",
    "**/tests/security.test.js",
    "**/tests/cors_security.test.js",
    "**/tests/fso_api.test.js",
    "**/tests/models.test.js",
    "**/tests/no_mongoose_runtime.test.js",
    "**/tests/prisma_admin_routes.test.js",
    "**/tests/prisma_vendor_routes.test.js",
    "**/tests/financial_idempotency.test.js",
    "**/tests/shiprocket_prisma.test.js",
    "**/tests/cart_order_integrity.test.js",
    "**/tests/razorpay_payment_integrity.test.js",
    "**/tests/shiprocket_logistics_integrity.test.js",
    "**/tests/seller_portal_integrity.test.js",
    "**/tests/admin_portal_integrity.test.js",
  ],
  verbose: true,
  forceExit: true,
  detectOpenHandles: true,
};
